// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"log"
	"flag"
	"context"
	"net/http"

	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime"
	//"github.com/jessevdk/go-flags"
	"github.com/pion/webrtc/v3"
	"github.com/opencameras/opencamd/gen/opencamera/models"
	"github.com/opencameras/opencamd/gen/opencamera/restapi"
	"github.com/opencameras/opencamd/gen/opencamera/restapi/operations"
	"github.com/opencameras/opencamd/gen/opencamera/restapi/operations/media"
	mediaImpl "github.com/opencameras/opencamd/pkg/media"
)

func createAPIBackend(swaggerSpec *loads.Document, videoSource mediaImpl.Datasource) *operations.OpenCameraAPI {
	api := operations.NewOpenCameraAPI(swaggerSpec)

	api.JSONConsumer = runtime.JSONConsumer()

	api.BasicAuthAuth = func(user string, pass string) (*models.User, error) {
		return &models.User{}, nil
	}
	api.KeyAuth = func(token string) (*models.User, error) {
		return &models.User{}, nil
	}
	api.MediaStartLiveSessionHandler = media.StartLiveSessionHandlerFunc(
		func(params media.StartLiveSessionParams, principal *models.User) middleware.Responder {
			m := &mediaImpl.WebrtcSession{
				VideoSource: videoSource,
				StunServers: []string{"stun:stun.l.google.com:19302"},
			}
			closeChan := make(chan struct{})
			sdp, err := m.Start(webrtc.SessionDescription{
				Type: webrtc.NewSDPType(params.Body.Type),
				SDP: params.Body.Sdp,
			}, closeChan)
			if err != nil {
				return middleware.Error(http.StatusInternalServerError, err)
			}
			return media.NewStartLiveSessionOK().WithPayload(&models.SDP{
				Type: sdp.Type.String(),
				Sdp: sdp.SDP,
			})
	})

	return api
}

func main() {
	var (
		err error
		localFilename string
		apiListenPort int
		mediaListenAddr string
		videoSource mediaImpl.Datasource
	)
	flag.StringVar(&localFilename, "f", "", "local file name as simulation purpose")
	flag.StringVar(&mediaListenAddr, "la", "localhost:8001", "tcp media server listen address for ffmpeg to stream")
	flag.IntVar(&apiListenPort, "lp", 8000, "API server listen port")

	flag.Parse()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	if localFilename != "" {
		videoSource = &mediaImpl.LocalFile{Filename: localFilename}
	} else {
		videoSource, err = mediaImpl.NewTcpSocketServer(ctx, mediaListenAddr)
		if err != nil {
			log.Fatal(err)
		}
		ffmpeg := mediaImpl.NewFfmpeg("0", 30.0, 1280, 720)
		ffmpeg.Start(ctx, "tcp://" + mediaListenAddr)
	}
	defer videoSource.Close()

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	api := createAPIBackend(swaggerSpec, videoSource)
	server := restapi.NewServer(api)
	defer server.Shutdown()

	server.Port = apiListenPort
	/*
	parser := flags.NewParser(server, flags.Default)
	parser.ShortDescription = "Opencamd"
	parser.LongDescription = "Open camera reference daemon"
	server.ConfigureFlags()
	for _, optsGroup := range api.CommandLineOptionsGroups {
		_, err := parser.AddGroup(optsGroup.ShortDescription, optsGroup.LongDescription, optsGroup.Options)
		if err != nil {
			log.Fatalln(err)
		}
	}

	if _, err := parser.Parse(); err != nil {
		code := 1
		if fe, ok := err.(*flags.Error); ok {
			if fe.Type == flags.ErrHelp {
				code = 0
			}
		}
		os.Exit(code)
	}
	*/
	server.ConfigureAPI()

	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}
}
